import {getStore} from '@netlify/blobs';
import sharp from 'sharp';

const store=()=>getStore('cloud-catcher');
const now=()=>new Date().toISOString();
const types=()=>[['cirrus','Cirrus','Ci','high'],['cirrocumulus','Cirrocumulus','Cc','high'],['cirrostratus','Cirrostratus','Cs','high'],['altocumulus','Altocumulus','Ac','middle'],['altostratus','Altostratus','As','middle'],['nimbostratus','Nimbostratus','Ns','middle'],['stratocumulus','Stratocumulus','Sc','low'],['stratus','Stratus','St','low'],['cumulus','Cumulus','Cu','vertical'],['cumulonimbus','Cumulonimbus','Cb','vertical']].map(([id,name,code,family])=>({id,name,code,family,level:1}));
const empty=()=>({format:'cloud-catcher',sessions:[],photos:[],detections:[],albums:[],updatedAt:now()});
async function load(){const lib=await store().get('library',{type:'json'})||empty();if(!Array.isArray(lib.sessions))lib.sessions=[];return lib}
async function save(lib){lib.updatedAt=now();await store().setJSON('library',lib);return lib}
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}});
const clamp=v=>Math.max(0,Math.min(1,Number(v)));
const validStatus=s=>['proposed','confirmed','rejected'].includes(s);
function normalizeRegion(region){if(!region)return{type:'rect',x:0,y:0,width:1,height:1};if(region.type==='rect'){const x=clamp(region.x),y=clamp(region.y),width=clamp(region.width),height=clamp(region.height);return{type:'rect',x,y,width:Math.min(width,1-x),height:Math.min(height,1-y)}}if(region.type==='polygon'&&Array.isArray(region.points)&&region.points.length>=3)return{type:'polygon',points:region.points.map(([x,y])=>[clamp(x),clamp(y)])};throw new Error('invalid region')}
function bounds(region){if(region.type==='rect')return region;const xs=region.points.map(p=>p[0]),ys=region.points.map(p=>p[1]),x=Math.min(...xs),y=Math.min(...ys);return{x,y,width:Math.max(...xs)-x,height:Math.max(...ys)-y}}
function parseDataUrl(dataUrl){const m=/^data:([^;]+);base64,(.+)$/.exec(dataUrl||'');if(!m)throw new Error('imageDataUrl must be a base64 data URL');return{mime:m[1],buffer:Buffer.from(m[2],'base64')}}
function progress(lib,location=null){const photos=new Map(lib.photos.map(p=>[p.id,p]));const caught=new Set(lib.detections.filter(d=>d.status==='confirmed').filter(d=>{const p=photos.get(d.photoId);return p&&(!location||p.location.toLowerCase()===location.toLowerCase())}).map(d=>d.cloudTypeId));const all=types();return{level:1,location,caught:all.filter(c=>caught.has(c.id)).length,required:all.length,complete:all.every(c=>caught.has(c.id)),missingIds:all.filter(c=>!caught.has(c.id)).map(c=>c.id)}}
function makeDetection(lib,photoId,b){if(!types().some(c=>c.id===b.cloudTypeId))throw new Error(`invalid cloudTypeId: ${b.cloudTypeId}`);const status=b.status||'proposed';if(!validStatus(status))throw new Error('invalid status');const d={id:crypto.randomUUID(),photoId,cloudTypeId:b.cloudTypeId,confidence:b.confidence==null?null:clamp(b.confidence),region:normalizeRegion(b.region),status,notes:b.notes||'',source:b.source||'api',createdAt:now(),updatedAt:now()};lib.detections.push(d);return d}
async function makePhoto(lib,b,defaults={}){const id=crypto.randomUUID();let imageRef=b.imageRef||null,width=b.width??null,height=b.height??null;if(b.imageDataUrl){const parsed=parseDataUrl(b.imageDataUrl);const meta=await sharp(parsed.buffer).metadata();width=meta.width??width;height=meta.height??height;await store().set(`images/${id}`,parsed.buffer);await store().setJSON(`images/${id}.meta`,{mime:parsed.mime});imageRef=`/api/images/${id}`}const p={id,sessionId:b.sessionId||defaults.sessionId||null,location:b.location||defaults.location||'Unknown',observedAt:b.observedAt||defaults.observedAt||now(),imageRef,originalName:b.originalName||null,notes:b.notes||'',source:b.source||defaults.source||'api',width,height,createdAt:now()};lib.photos.push(p);if(p.sessionId){const s=lib.sessions.find(x=>x.id===p.sessionId);if(!s)throw new Error('invalid sessionId');if(!s.photoIds.includes(p.id))s.photoIds.push(p.id)}return p}
async function makeCatch(lib,b,defaults={}){const p=await makePhoto(lib,b,defaults);const ds=(b.detections||[]).map(d=>makeDetection(lib,p.id,{...d,source:d.source||b.source||defaults.source}));return{photo:p,detections:ds.map(d=>({...d,snippetRef:`/api/snippets/${d.id}`}))}}
function ensureSession(lib,{name='San Sebastián clouds',location='San Sebastián',observedAt=now(),source='ai'}={}){let s=lib.sessions.find(x=>x.name===name);if(!s){s={id:crypto.randomUUID(),name,location,observedAt,notes:'First real Cloud Catcher batch',source,photoIds:[],createdAt:now()};lib.sessions.push(s)}return s}

export default async request=>{
  const url=new URL(request.url),path=url.pathname.replace(/^\/api\/?/,'').split('/').filter(Boolean),resource=path[0]||'status',id=path[1];
  if(resource==='status')return json({name:'Cloud Catcher API',writesEnabled:true});
  if(resource==='cloud-types'){const all=types(),item=id?all.find(c=>c.id===id):all;return item?json(item):json({error:'not found'},404)}
  const lib=await load();
  if(resource==='progress'&&request.method==='GET')return json(progress(lib,url.searchParams.get('location')));
  if(resource==='sessions'){
    if(request.method==='GET'){const item=id?lib.sessions.find(s=>s.id===id):lib.sessions;return item?json(item):json({error:'not found'},404)}
    if(request.method==='POST'){const b=await request.json(),s={id:crypto.randomUUID(),name:b.name||'Cloud session',location:b.location||'Unknown',observedAt:b.observedAt||now(),notes:b.notes||'',source:b.source||'api',photoIds:[],createdAt:now()};lib.sessions.push(s);await save(lib);return json(s,201)}
  }
  if(resource==='catches'&&request.method==='POST'){
    try{if(id==='batch'){const b=await request.json(),defaults=b.defaults||{};let session=null;if(b.session){session={id:crypto.randomUUID(),name:b.session.name||'Cloud session',location:b.session.location||defaults.location||'Unknown',observedAt:b.session.observedAt||defaults.observedAt||now(),notes:b.session.notes||'',source:b.session.source||defaults.source||'api',photoIds:[],createdAt:now()};lib.sessions.push(session);defaults.sessionId=session.id;defaults.location=defaults.location||session.location;defaults.observedAt=defaults.observedAt||session.observedAt;defaults.source=defaults.source||session.source}const results=[];for(const item of b.catches||[])results.push(await makeCatch(lib,item,defaults));await save(lib);return json({session,results,summary:{photos:results.length,detections:results.reduce((n,r)=>n+r.detections.length,0)}},201)}const result=await makeCatch(lib,await request.json());await save(lib);return json(result,201)}catch(e){return json({error:e.message},400)}
  }
  if(resource==='seed-catch'&&request.method==='GET'){
    try{const q=url.searchParams,name=q.get('name')||'cloud.jpg',image=q.get('image');if(!image)throw new Error('missing image');const session=ensureSession(lib);const detections=[];for(let i=1;i<=2;i++){const cloudTypeId=q.get(`type${i}`);if(!cloudTypeId)continue;detections.push({cloudTypeId,confidence:Number(q.get(`confidence${i}`)||0.9),status:q.get(`status${i}`)||'confirmed',region:{type:'rect',x:Number(q.get(`x${i}`)||0),y:Number(q.get(`y${i}`)||0),width:Number(q.get(`w${i}`)||1),height:Number(q.get(`h${i}`)||0.75)},source:'ai'})}const result=await makeCatch(lib,{sessionId:session.id,location:'San Sebastián',originalName:name,imageDataUrl:`data:image/jpeg;base64,${image}`,source:'ai',detections});await save(lib);return json({sessionId:session.id,...result},201)}catch(e){return json({error:e.message},400)}
  }
  if(resource==='photos'){
    if(request.method==='GET'){const item=id?lib.photos.find(p=>p.id===id):lib.photos;return item?json(item):json({error:'not found'},404)}
    if(request.method==='POST'){try{const p=await makePhoto(lib,await request.json());await save(lib);return json(p,201)}catch(e){return json({error:e.message},400)}}
    if(request.method==='DELETE'&&id){lib.photos=lib.photos.filter(p=>p.id!==id);lib.sessions.forEach(s=>s.photoIds=s.photoIds.filter(x=>x!==id));const removed=new Set(lib.detections.filter(d=>d.photoId===id).map(d=>d.id));lib.detections=lib.detections.filter(d=>d.photoId!==id);lib.albums.forEach(a=>a.detectionIds=(a.detectionIds||[]).filter(x=>!removed.has(x)));await store().delete(`images/${id}`);await store().delete(`images/${id}.meta`);await save(lib);return json({deleted:id})}
  }
  if(resource==='detections'){
    if(request.method==='GET'){const item=id?lib.detections.find(d=>d.id===id):lib.detections;return item?json(item):json({error:'not found'},404)}
    if(request.method==='POST'){try{const b=await request.json();if(!lib.photos.some(p=>p.id===b.photoId))return json({error:'invalid photoId'},400);const d=makeDetection(lib,b.photoId,b);await save(lib);return json({...d,snippetRef:`/api/snippets/${d.id}`},201)}catch(e){return json({error:e.message},400)}}
    if(request.method==='PATCH'&&id){const b=await request.json(),d=lib.detections.find(x=>x.id===id);if(!d)return json({error:'not found'},404);if(b.cloudTypeId!==undefined){if(!types().some(c=>c.id===b.cloudTypeId))return json({error:'invalid cloudTypeId'},400);d.cloudTypeId=b.cloudTypeId}if(b.status!==undefined){if(!validStatus(b.status))return json({error:'invalid status'},400);d.status=b.status}if(b.confidence!==undefined)d.confidence=b.confidence==null?null:clamp(b.confidence);if(b.region!==undefined)d.region=normalizeRegion(b.region);if(b.notes!==undefined)d.notes=b.notes;d.updatedAt=now();await save(lib);return json({...d,snippetRef:`/api/snippets/${d.id}`})}
    if(request.method==='DELETE'&&id){lib.detections=lib.detections.filter(d=>d.id!==id);lib.albums.forEach(a=>a.detectionIds=(a.detectionIds||[]).filter(x=>x!==id));await save(lib);return json({deleted:id})}
  }
  if(resource==='images'&&request.method==='GET'&&id){const image=await store().get(`images/${id}`,{type:'arrayBuffer'});if(!image)return json({error:'not found'},404);const meta=await store().get(`images/${id}.meta`,{type:'json'});return new Response(image,{headers:{'content-type':meta?.mime||'image/jpeg','cache-control':'public, max-age=31536000, immutable'}})}
  if(resource==='snippets'&&request.method==='GET'&&id){const d=lib.detections.find(x=>x.id===id);if(!d)return json({error:'not found'},404);const p=lib.photos.find(x=>x.id===d.photoId);if(!p)return json({error:'photo not found'},404);const image=await store().get(`images/${p.id}`,{type:'arrayBuffer'});if(!image)return json({error:'source image unavailable'},404);const input=Buffer.from(image),meta=await sharp(input).metadata(),b=bounds(d.region),left=Math.max(0,Math.floor(b.x*meta.width)),top=Math.max(0,Math.floor(b.y*meta.height)),width=Math.max(1,Math.min(meta.width-left,Math.ceil(b.width*meta.width))),height=Math.max(1,Math.min(meta.height-top,Math.ceil(b.height*meta.height))),cropped=await sharp(input).extract({left,top,width,height}).jpeg({quality:88}).toBuffer();return new Response(cropped,{headers:{'content-type':'image/jpeg','cache-control':'public, max-age=86400'}})}
  if(resource==='albums'){
    if(request.method==='GET'){const item=id?lib.albums.find(a=>a.id===id):lib.albums;return item?json(item):json({error:'not found'},404)}
    if(request.method==='POST'){const b=await request.json(),a={id:crypto.randomUUID(),name:b.name||'Untitled album',location:b.location||null,level:b.level||1,detectionIds:[],createdAt:now()};lib.albums.push(a);await save(lib);return json(a,201)}
    if(request.method==='PATCH'&&id){const b=await request.json(),a=lib.albums.find(x=>x.id===id);if(!a)return json({error:'not found'},404);if(Array.isArray(b.detectionIds))a.detectionIds=[...new Set(b.detectionIds.filter(did=>lib.detections.some(d=>d.id===did)))];if(typeof b.name==='string')a.name=b.name;await save(lib);return json(a)}
  }
  return json({error:'not found'},404)
};
export const config={path:'/api/*'};
