import {LEVEL_ONE,getCloudType} from './src/taxonomy.js';
import {addDetection,addPhoto,levelProgress,locationCollections,makeDetection,makePhoto,updateDetection} from './src/domain.js';
import {BrowserStorageProvider,downloadBlob} from './src/storage.js';

const storage=new BrowserStorageProvider();
let library=await storage.loadLibrary();
let current=LEVEL_ONE[Math.floor(Math.random()*LEVEL_ONE.length)];
let answered=false;let pendingImage=null;
const views={catch:document.querySelector('#catch-view'),atlas:document.querySelector('#atlas-view'),data:document.querySelector('#data-view')};

document.querySelectorAll('nav button').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.view)));
function showView(name){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));Object.entries(views).forEach(([k,v])=>v.classList.toggle('active',k===name));render()}
function shuffle(a){return[...a].sort(()=>Math.random()-.5)}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
const fileDataUrl=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});
const imageSize=src=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve({width:img.naturalWidth,height:img.naturalHeight});img.onerror=reject;img.src=src});
async function cropDataUrl(src,region){const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=src});const b=region.type==='rect'?region:(()=>{const xs=region.points.map(p=>p[0]),ys=region.points.map(p=>p[1]);const x=Math.min(...xs),y=Math.min(...ys);return{x,y,width:Math.max(...xs)-x,height:Math.max(...ys)-y}})();const sx=Math.floor(b.x*img.naturalWidth),sy=Math.floor(b.y*img.naturalHeight),sw=Math.max(1,Math.ceil(b.width*img.naturalWidth)),sh=Math.max(1,Math.ceil(b.height*img.naturalHeight));const canvas=document.createElement('canvas');canvas.width=sw;canvas.height=sh;canvas.getContext('2d').drawImage(img,sx,sy,sw,sh,0,0,sw,sh);return canvas.toDataURL('image/jpeg',.88)}

function render(){renderCatch();renderAtlas();renderData()}
function renderCatch(){
  const choices=shuffle([current,...shuffle(LEVEL_ONE.filter(c=>c.id!==current.id)).slice(0,3)]);
  views.catch.innerHTML=`<div class="hero"><div><p class="eyebrow">Level 1 · 10 genera</p><h2>What cloud did you catch?</h2><p>Learn the ten principal cloud genera by identifying them and building your personal atlas.</p><label>Location<br><input id="location" type="text" value="San Sebastián" aria-label="Observation location"></label><div class="choices">${choices.map(c=>`<button data-choice="${c.id}">${c.name}</button>`).join('')}</div><div id="feedback"></div></div><div class="sky-stage" aria-label="Stylized cloud challenge"></div></div><div class="panel"><p class="eyebrow">Real sky</p><h2>Catch clouds from a photo</h2><p>One photo can contain several cloud types. Upload it once, then add one or more detections. Each detection stores its own crop region and can become a separate Atlas card.</p><div class="upload-grid"><div><label class="button file-label">Choose photo<input id="photo-file" type="file" accept="image/*"></label><div id="photo-preview">${pendingImage?`<img class="photo-preview" src="${pendingImage.dataUrl}" alt="Uploaded cloud photo">`:'<p class="muted">No photo selected.</p>'}</div></div><div>${pendingImage?detectionForm():''}</div></div><div id="upload-feedback"></div></div>`;
  views.catch.querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>answer(b.dataset.choice)));
  document.querySelector('#photo-file').addEventListener('change',loadPhoto);
  document.querySelector('#save-detection')?.addEventListener('click',saveRealDetection);
}
function detectionForm(){return`<label>Location<br><input id="photo-location" value="San Sebastián"></label><label>Cloud type<br><select id="det-type">${LEVEL_ONE.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select></label><label>Confidence (0–100%)<br><input id="det-confidence" type="number" min="0" max="100" value="90"></label><fieldset><legend>Crop region (% of photo)</legend><div class="region-grid"><label>Left<input id="det-x" type="number" min="0" max="100" value="0"></label><label>Top<input id="det-y" type="number" min="0" max="100" value="0"></label><label>Width<input id="det-w" type="number" min="1" max="100" value="100"></label><label>Height<input id="det-h" type="number" min="1" max="100" value="70"></label></div></fieldset><div class="toolbar"><button id="save-detection" class="primary">Add confirmed cloud</button></div><p class="muted">Add another detection afterward to catch a second cloud type from the same photograph.</p>`}
async function loadPhoto(e){const file=e.target.files?.[0];if(!file)return;const dataUrl=await fileDataUrl(file);const size=await imageSize(dataUrl);pendingImage={file,dataUrl,...size,photoId:null};render()}
async function saveRealDetection(){const location=document.querySelector('#photo-location').value||'Unknown';if(!pendingImage.photoId){const photo=makePhoto({location,imageRef:pendingImage.dataUrl,originalName:pendingImage.file.name,width:pendingImage.width,height:pendingImage.height,source:'upload'});library=addPhoto(library,photo);pendingImage.photoId=photo.id}else{const photo=library.photos.find(p=>p.id===pendingImage.photoId);if(photo)photo.location=location}const pct=id=>Math.max(0,Math.min(100,Number(document.querySelector(id).value)))/100;const region={type:'rect',x:pct('#det-x'),y:pct('#det-y'),width:pct('#det-w'),height:pct('#det-h')};const detection=makeDetection({photoId:pendingImage.photoId,cloudTypeId:document.querySelector('#det-type').value,confidence:Number(document.querySelector('#det-confidence').value)/100,region,status:'confirmed',source:'manual-upload'});detection.snippetRef=await cropDataUrl(pendingImage.dataUrl,detection.region);library=addDetection(library,detection);await storage.saveLibrary(library);document.querySelector('#upload-feedback').innerHTML=`<div class="feedback"><strong>Caught!</strong> ${getCloudType(detection.cloudTypeId).name} was added from this photo. You can add another cloud from the same image.</div>`;renderAtlas();renderData()}
async function answer(id){
  if(answered)return;answered=true;const correct=id===current.id;const type=getCloudType(current.id);const feedback=document.querySelector('#feedback');
  if(correct){const location=document.querySelector('#location').value||'Unknown';const photo=makePhoto({location,source:'quiz'});library=addPhoto(library,photo);library=addDetection(library,makeDetection({photoId:photo.id,cloudTypeId:current.id,status:'confirmed',source:'quiz'}));await storage.saveLibrary(library)}
  feedback.innerHTML=`<div class="feedback"><strong>${correct?'Caught!':'Not quite.'}</strong> This is <b>${type.name}</b>. ${type.clue}<div class="toolbar"><button id="next" class="primary">Next cloud</button></div></div>`;
  document.querySelector('#next').addEventListener('click',()=>{current=LEVEL_ONE[Math.floor(Math.random()*LEVEL_ONE.length)];answered=false;render()})
}
function renderAtlas(){
  const progress=levelProgress(library);const caught=new Set(progress.caughtIds);const locations=locationCollections(library);const confirmed=library.detections.filter(d=>d.status==='confirmed');
  views.atlas.innerHTML=`<div class="panel"><p class="eyebrow">Cloud Atlas</p><h2>Level 1 collection</h2><div class="stats"><div class="stat"><strong>${progress.caught}/${progress.required}</strong>types caught</div><div class="stat"><strong>${progress.complete?'Complete':'In progress'}</strong>level status</div><div class="stat"><strong>${library.photos.length}</strong>photos</div><div class="stat"><strong>${confirmed.length}</strong>confirmed clouds</div></div><div class="grid">${LEVEL_ONE.map(c=>{const d=confirmed.find(x=>x.cloudTypeId===c.id);return`<article class="cloud-card ${caught.has(c.id)?'':'locked'}">${d?.snippetRef?`<img class="card-photo" src="${d.snippetRef}" alt="${c.name} crop">`:'<div class="cloud-art"></div>'}<div class="cloud-copy"><p class="cloud-code">${c.code} · ${c.family}</p><h3>${caught.has(c.id)?c.name:'Unknown cloud'}</h3><p class="cloud-summary">${caught.has(c.id)?c.summary:'Catch this genus to reveal its card.'}</p>${d?.confidence!=null?`<p>${Math.round(d.confidence*100)}% confidence</p>`:''}</div></article>`}).join('')}</div><h2>Location cards</h2><div class="grid">${locations.length?locations.map(p=>`<article class="cloud-card ${p.complete?'':'locked'}"><div class="cloud-art"></div><div class="cloud-copy"><p class="cloud-code">Level ${p.level}</p><h3>${escapeHtml(p.location)}</h3><p>${p.caught}/${p.required} cloud genera caught here${p.complete?' · Location card unlocked!':''}</p></div></article>`).join(''):'<p>No locations caught yet.</p>'}</div></div>`
}
function renderData(){
  const proposed=library.detections.filter(d=>d.status==='proposed').length;
  views.data.innerHTML=`<div class="panel"><p class="eyebrow">Your data</p><h2>Portable by design</h2><p>Your browser copy is offline-first. Export it whenever you want. Photos are stored separately from cloud detections, so one image can contribute multiple cloud cards.</p><div class="toolbar"><button id="export" class="primary">Export library</button><label class="button file-label">Import library<input id="import" type="file" accept="application/json,.json"></label></div><p><b>${library.photos.length}</b> photos · <b>${library.detections.length}</b> detections · <b>${proposed}</b> awaiting confirmation · <b>${library.albums.length}</b> albums</p><hr><h3>AI API</h3><p>Upload an image with <code>POST /api/photos</code>, add any number of AI detections with <code>POST /api/detections</code>, review them with <code>PATCH /api/detections/:id</code>, and retrieve a cropped JPEG for each cloud at <code>/api/snippets/:detectionId</code>.</p><h3>Google Drive</h3><p>The Drive provider uses the same portable library schema. Image-file synchronization is the next adapter extension; the data format itself is not tied to Drive or Netlify.</p></div>`;
  document.querySelector('#export').addEventListener('click',async()=>downloadBlob(await storage.exportArchive(library),`cloud-catcher-${new Date().toISOString().slice(0,10)}.json`));
  document.querySelector('#import').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;library=await storage.importArchive(file);await storage.saveLibrary(library);render()})
}

window.cloudCatcher={getLibrary:()=>structuredClone(library),getCloudTypes:()=>structuredClone(LEVEL_ONE),getProgress:(location=null)=>levelProgress(library,1,location),addPhoto:async data=>{const p=makePhoto(data);library=addPhoto(library,p);await storage.saveLibrary(library);render();return structuredClone(p)},addDetection:async data=>{const d=makeDetection(data);library=addDetection(library,d);await storage.saveLibrary(library);render();return structuredClone(d)},updateDetection:async(id,patch)=>{library=updateDetection(library,id,patch);await storage.saveLibrary(library);render();return structuredClone(library.detections.find(d=>d.id===id))}};
render();
