import {LEVEL_ONE,getCloudType} from './taxonomy.js';
export const FORMAT='cloud-catcher';
const now=()=>new Date().toISOString();
const uuid=()=>crypto.randomUUID();

export function emptyLibrary(){const t=now();return{format:FORMAT,taxonomyVersion:'1.0',photos:[],detections:[],albums:[],createdAt:t,updatedAt:t}}
export function makePhoto({location='Unknown',observedAt=now(),imageRef=null,originalName=null,notes='',source='manual',width=null,height=null}){return{id:uuid(),location:location.trim()||'Unknown',observedAt,imageRef,originalName,notes,source,width,height,createdAt:now()}}
export function normalizeRegion(region){if(!region)return{type:'rect',x:0,y:0,width:1,height:1};if(region.type==='rect'){const clamp=v=>Math.max(0,Math.min(1,Number(v)));const x=clamp(region.x),y=clamp(region.y),width=clamp(region.width),height=clamp(region.height);return{type:'rect',x,y,width:Math.min(width,1-x),height:Math.min(height,1-y)}}if(region.type==='polygon'&&Array.isArray(region.points)&&region.points.length>=3){return{type:'polygon',points:region.points.map(([x,y])=>[Math.max(0,Math.min(1,Number(x))),Math.max(0,Math.min(1,Number(y)))])}}throw new Error('Invalid detection region')}
export function makeDetection({photoId,cloudTypeId,confidence=null,region=null,status='proposed',notes='',source='manual'}){if(!photoId)throw new Error('photoId is required');if(!getCloudType(cloudTypeId))throw new Error(`Unknown cloud type: ${cloudTypeId}`);if(!['proposed','confirmed','rejected'].includes(status))throw new Error('Invalid detection status');return{id:uuid(),photoId,cloudTypeId,confidence:confidence==null?null:Math.max(0,Math.min(1,Number(confidence))),region:normalizeRegion(region),status,notes,source,createdAt:now(),updatedAt:now()}}
export function makeAlbum({name,location=null,level=1,automatic=false}){return{id:uuid(),name,location,level,automatic,detectionIds:[],createdAt:now()}}
export function addPhoto(library,photo){const next=structuredClone(library);next.photos.push(photo);next.updatedAt=now();return next}
export function addDetection(library,detection){if(!library.photos.some(p=>p.id===detection.photoId))throw new Error('Photo not found');const next=structuredClone(library);next.detections.push(detection);next.updatedAt=now();return next}
export function updateDetection(library,detectionId,patch){const next=structuredClone(library);const detection=next.detections.find(d=>d.id===detectionId);if(!detection)throw new Error('Detection not found');if(patch.cloudTypeId!==undefined){if(!getCloudType(patch.cloudTypeId))throw new Error(`Unknown cloud type: ${patch.cloudTypeId}`);detection.cloudTypeId=patch.cloudTypeId}if(patch.confidence!==undefined)detection.confidence=patch.confidence==null?null:Math.max(0,Math.min(1,Number(patch.confidence)));if(patch.region!==undefined)detection.region=normalizeRegion(patch.region);if(patch.status!==undefined){if(!['proposed','confirmed','rejected'].includes(patch.status))throw new Error('Invalid detection status');detection.status=patch.status}if(patch.notes!==undefined)detection.notes=patch.notes;detection.updatedAt=now();next.updatedAt=now();return next}
export function addDetectionToAlbum(library,albumId,detectionId){const next=structuredClone(library);const album=next.albums.find(a=>a.id===albumId);if(!album)throw new Error('Album not found');if(!next.detections.some(d=>d.id===detectionId))throw new Error('Detection not found');if(!album.detectionIds.includes(detectionId))album.detectionIds.push(detectionId);next.updatedAt=now();return next}
export function confirmedDetections(library,location=null){const photos=new Map(library.photos.map(p=>[p.id,p]));return library.detections.filter(d=>d.status==='confirmed').filter(d=>{const p=photos.get(d.photoId);return p&&(!location||p.location.toLocaleLowerCase()===location.toLocaleLowerCase())})}
export function levelProgress(library,level=1,location=null){const required=LEVEL_ONE.filter(c=>c.level===level);const caught=new Set(confirmedDetections(library,location).map(d=>d.cloudTypeId));const caughtIds=required.filter(c=>caught.has(c.id)).map(c=>c.id);return{level,location,caught:caughtIds.length,required:required.length,complete:caughtIds.length===required.length,caughtIds,missingIds:required.filter(c=>!caught.has(c.id)).map(c=>c.id)}}
export function locationCollections(library,level=1){return[...new Set(library.photos.map(p=>p.location))].sort().map(location=>levelProgress(library,level,location))}
export function validateLibrary(value){if(!value||value.format!==FORMAT)throw new Error('Not a Cloud Catcher archive');if(!Array.isArray(value.photos)||!Array.isArray(value.detections)||!Array.isArray(value.albums))throw new Error('Invalid Cloud Catcher library');return value}
