import {LEVEL_ONE,getCloudType} from './taxonomy.js';
export const FORMAT='cloud-catcher';export const FORMAT_VERSION=1;
export function emptyLibrary(){return{format:FORMAT,formatVersion:FORMAT_VERSION,taxonomyVersion:'1.0',observations:[],albums:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}
export function makeObservation({cloudTypeId,location='Unknown',observedAt=new Date().toISOString(),imageRef=null,notes='',confidence=null,source='manual'}){if(!getCloudType(cloudTypeId))throw new Error(`Unknown cloud type: ${cloudTypeId}`);return{id:crypto.randomUUID(),cloudTypeId,location:location.trim()||'Unknown',observedAt,imageRef,notes,confidence,source,createdAt:new Date().toISOString()}}
export function makeAlbum({name,location=null,level=1,automatic=false}){return{id:crypto.randomUUID(),name,location,level,automatic,observationIds:[],createdAt:new Date().toISOString()}}
export function addObservation(library,observation){const next=structuredClone(library);next.observations.push(observation);next.updatedAt=new Date().toISOString();return next}
export function addAlbum(library,album){const next=structuredClone(library);next.albums.push(album);next.updatedAt=new Date().toISOString();return next}
export function addObservationToAlbum(library,albumId,observationId){const next=structuredClone(library);const album=next.albums.find(a=>a.id===albumId);if(!album)throw new Error('Album not found');if(!next.observations.some(o=>o.id===observationId))throw new Error('Observation not found');if(!album.observationIds.includes(observationId))album.observationIds.push(observationId);next.updatedAt=new Date().toISOString();return next}
export function levelProgress(library,level=1,location=null){const required=LEVEL_ONE.filter(c=>c.level===level);const obs=library.observations.filter(o=>!location||o.location.toLocaleLowerCase()===location.toLocaleLowerCase());const caught=new Set(obs.map(o=>o.cloudTypeId));const caughtIds=required.filter(c=>caught.has(c.id)).map(c=>c.id);return{level,location,caught:caughtIds.length,required:required.length,complete:caughtIds.length===required.length,caughtIds,missingIds:required.filter(c=>!caught.has(c.id)).map(c=>c.id)}}
export function locationCollections(library,level=1){return[...new Set(library.observations.map(o=>o.location))].sort().map(location=>levelProgress(library,level,location))}
export function validateLibrary(value){if(!value||value.format!==FORMAT)throw new Error('Not a Cloud Catcher archive');if(value.formatVersion!==FORMAT_VERSION)throw new Error(`Unsupported archive version: ${value.formatVersion}`);if(!Array.isArray(value.observations)||!Array.isArray(value.albums))throw new Error('Invalid Cloud Catcher library');return value}
