export const LEVEL_ONE=[
{id:'cirrus',name:'Cirrus',code:'Ci',level:1,parentId:null,family:'high',summary:'Thin, fibrous ice-cloud streaks high in the sky.',clue:'Look for wispy hair-like filaments.',referenceImage:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Cirrus_cloud.jpg?width=800',referencePage:'https://commons.wikimedia.org/wiki/File:Cirrus_cloud.jpg'},
{id:'cirrocumulus',name:'Cirrocumulus',code:'Cc',level:1,parentId:null,family:'high',summary:'Tiny rippled cloudlets in high-level sheets.',clue:'Very small grains or ripples, often a mackerel-sky pattern.',referenceImage:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Cirrocumulus.jpg?width=800',referencePage:'https://commons.wikimedia.org/wiki/File:Cirrocumulus.jpg'},
{id:'cirrostratus',name:'Cirrostratus',code:'Cs',level:1,parentId:null,family:'high',summary:'A thin high veil that can cover much of the sky.',clue:'Often produces a halo around the Sun or Moon.',referenceImage:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Cirrostratus.jpg?width=800',referencePage:'https://commons.wikimedia.org/wiki/File:Cirrostratus.jpg'},
{id:'altocumulus',name:'Altocumulus',code:'Ac',level:1,parentId:null,family:'middle',summary:'Mid-level patches or rolls made of rounded cloud elements.',clue:'Cloudlets look larger than cirrocumulus but smaller than stratocumulus.',referenceImage:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Altocumulus_cloud.jpg?width=800',referencePage:'https://commons.wikimedia.org/wiki/File:Altocumulus_cloud.jpg'},
{id:'altostratus',name:'Altostratus',code:'As',level:1,parentId:null,family:'middle',summary:'A broad gray or blue-gray mid-level sheet.',clue:'The Sun may show dimly through it, without a halo.',referenceImage:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Altostratus_clouds.jpg?width=800',referencePage:'https://commons.wikimedia.org/wiki/File:Altostratus_clouds.jpg'},
{id:'nimbostratus',name:'Nimbostratus',code:'Ns',level:1,parentId:null,family:'middle',summary:'A thick, dark layer associated with widespread steady precipitation.',clue:'Featureless rain cloud covering much of the sky.',referenceImage:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Nimbostratus_clouds.jpg?width=800',referencePage:'https://commons.wikimedia.org/wiki/File:Nimbostratus_clouds.jpg'},
{id:'stratocumulus',name:'Stratocumulus',code:'Sc',level:1,parentId:null,family:'low',summary:'Low lumpy layers, rolls, or patches with broad cloud elements.',clue:'Large rounded masses arranged into a low sheet.',referenceImage:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Stratocumulus_Cloud.jpg?width=800',referencePage:'https://commons.wikimedia.org/wiki/File:Stratocumulus_Cloud.jpg'},
{id:'stratus',name:'Stratus',code:'St',level:1,parentId:null,family:'low',summary:'A low, uniform gray layer resembling lifted fog.',clue:'Flat, featureless, low cloud deck.',referenceImage:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Stratus_Cloud.jpg?width=800',referencePage:'https://commons.wikimedia.org/wiki/File:Stratus_Cloud.jpg'},
{id:'cumulus',name:'Cumulus',code:'Cu',level:1,parentId:null,family:'vertical',summary:'Detached heaps with crisp edges and relatively flat bases.',clue:'Classic cauliflower clouds with vertical growth.',referenceImage:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Cumulus_Cloud.jpg?width=800',referencePage:'https://commons.wikimedia.org/wiki/File:Cumulus_Cloud.jpg'},
{id:'cumulonimbus',name:'Cumulonimbus',code:'Cb',level:1,parentId:null,family:'vertical',summary:'Deep storm clouds with strong vertical development.',clue:'Towering cloud, often with an anvil-shaped top.',referenceImage:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Cumulonimbus_cloud.jpg?width=800',referencePage:'https://commons.wikimedia.org/wiki/File:Cumulonimbus_cloud.jpg'}
];
export const getCloudType=id=>LEVEL_ONE.find(c=>c.id===id)??null;
export const getChildren=parentId=>LEVEL_ONE.filter(c=>c.parentId===parentId);
